defaults:
  - data: la2a_100

epochs: 1000
ckpt_path: ckpt.yaml
compressor:
  inits:
    rms_avg: 0.9
    threshold: -36
    ratio: 4
    attack_ms: 1
    release_ms: 200
    make_up_gain: 0
  delay: 0
  init_config: null

loss_fn:
  _target_: torch.nn.MSELoss
  reduction: mean

optimiser:
  reg_lambda: 0.00001
  alpha: 0.5
  beta: 0.9
  max_iter: 20

wandb_init:
  project: la2a-newton
