defaults:
  - data: la2a_100

mode: forward
epochs: 100
ckpt_dir: /home/ycy/working/LA-2A-newton/fitted/la2a_100
compressor:
  inits:
    threshold: -36
    ratio: 4
    attack_ms: 1
    release_ms: 200
    make_up_gain: 0
  range:
    ratio:
      min: 1
      max: 20
    attack_ms:
      min: 0.1
      max: 100
    release_ms:
      min: 10
      max: 1000
  init_ckpt: null
  delay: 0

optimiser:
  method: direct
  alpha: 0.0001
  beta: 0.5
  max_iter: 20

wandb_init:
  project: la2a-newton
